### ISSUE TITLE
[Bug] Crash on Android 1.6

### ISSUE THREAD

**Issue by EatHatsuneShallots** [martinmimigames/little-file-explorer#82]
**Describe the bug**
Crash on Android 1.6

**To Reproduce**
Open this application

**Expected Behaviour**
No crash

**[Optional] Screenshots**
null

**[Optional] Versioning  information**
- App Version: v4.15
- OS: Android 1.6 x86

**[Optional] Additional information**
<details>
<summary>Logcat</summary>
<pre><blockcode>
E/dalvikvm( 2251): Could not find method android.app.Activity.recreate, referenced from method com.martinmimigames.simplefileexplorer.MainActivity.a
W/dalvikvm( 2251): VFY: unable to resolve virtual method 57: Landroid/app/Activity;.recreate ()V
W/dalvikvm( 2251): VFY:  rejecting opcode 0x6e at 0x002a
W/dalvikvm( 2251): VFY:  rejected Lcom/martinmimigames/simplefileexplorer/MainActivity;.a (Lcom/martinmimigames/simplefileexplorer/MainActivity;)V
W/dalvikvm( 2251): Verifier rejected class Lcom/martinmimigames/simplefileexplorer/MainActivity;
W/dalvikvm( 2251): Class init failed in newInstance call (Lcom/martinmimigames/simplefileexplorer/MainActivity;)
D/AndroidRuntime( 2251): Shutting down VM
W/dalvikvm( 2251): threadid=3: thread exiting with uncaught exception (group=0xa8011cf8)
E/AndroidRuntime( 2251): Uncaught handler: thread main exiting due to uncaught exception
E/AndroidRuntime( 2251): java.lang.VerifyError: com.martinmimigames.simplefileexplorer.MainActivity
E/AndroidRuntime( 2251): 	at java.lang.Class.newInstanceImpl(Native Method)
E/AndroidRuntime( 2251): 	at java.lang.Class.newInstance(Class.java:1472)
E/AndroidRuntime( 2251): 	at android.app.Instrumentation.newActivity(Instrumentation.java:1097)
E/AndroidRuntime( 2251): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2316)
E/AndroidRuntime( 2251): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2417)
E/AndroidRuntime( 2251): 	at android.app.ActivityThread.access$2100(ActivityThread.java:116)
E/AndroidRuntime( 2251): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794)
E/AndroidRuntime( 2251): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 2251): 	at android.os.Looper.loop(Looper.java:123)
E/AndroidRuntime( 2251): 	at android.app.ActivityThread.main(ActivityThread.java:4203)
E/AndroidRuntime( 2251): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 2251): 	at java.lang.reflect.Method.invoke(Method.java:521)
E/AndroidRuntime( 2251): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:791)
E/AndroidRuntime( 2251): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:549)
E/AndroidRuntime( 2251): 	at dalvik.system.NativeStart.main(Native Method)
</blockcode></pre>
</details>

**Comment by joriswit** [comment]
To build for very old Android versions, the problem surfaces that recent Android build tools use AAPT2, which uses UTF-8 instead of UTF-16 in the resources.arsc file. This causes it to not work on Android versions before Android 2.1, when UTF-8 support was added.

I believe this is the max version of tools:
- Compile SDK 29 (Target SDK can be higher)
- Android Studio 4.1.3
- Gradle 4.10.3
- Android Gradle Plugin 2.3.3

(I'm not really sure if really nothing can be upgraded, but this is what I use)

I tried to downgrade little-file-explorer, but was not successful in building.
